[package]
name = "flappy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["dynamic_linking", "debug"] }
bevy_simple_screen_boxing = "0.4.0"
rand = "0.10.2"
serde = "1.0.229"
serde_json = "1.0.151"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
